export const DEVICES_LOADING = 'DEVICES_LOADING';
export const ADD_DEVICES = 'ADD_DEVICES';
export const DEVICES_FAILED = 'DEVICES_FAILED';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const ADD_GROUPS = 'ADD_GROUPS';
export const GROUPS_FAILED = 'GROUPS_FAILED';
